S3 backed Bazel cache (#14)

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -7,5 +7,24 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: "16"
+          cache: "npm"
+      - run: npm install -g @bazel/bazelisk
+      - run: npm install -g bazels3cache
+      - name: Start Bazel cache
+        run: bazels3cache --bucket=dist.cloudpave.com
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
+          AWS_DEFAULT_REGION: "us-east-1"
       - name: Bazel build
-        run: bazel build java/org/cyclopsgroup/aoj/server
+        env:
+          BAZEL_BUILD_OPTS: "--remote_http_cache=http://localhost:7777/bazelcache/angular-on-java"
+        # The tomcat bundle can't be built for now since the remote cache is not yet
+        # happy with symlink that tomcat build rule uses.
+        run: bazel build $BAZEL_BUILD_OPTS //java/org/cyclopsgroup/aoj/server:war
+      - name: Stop Bazel cache
+        if: always()
+        run: curl http://localhost:7777/shutdown || echo "Ignore bazels3cache shutdown failure."
